# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [25]:
import numpy as np
import numpy.random as rnd

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [26]:
arr=rnd.rand(4,7)*20
arr=(arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(arr)

[[0.76502935 0.         0.97938488 0.0072084  0.11618517 0.91138566
  0.52896668]
 [0.54531334 0.96666575 0.27369413 0.2044484  0.93306918 0.34658917
  0.56962583]
 [0.95582208 0.85516622 0.965854   0.55563282 0.53641035 0.55224926
  0.42814857]
 [0.68291448 0.39529645 0.27898446 0.60517675 0.59377218 0.00637633
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [27]:
a=rnd.randint(10)
b=rnd.randint(10)

print(np.sqrt(np.sum(a*a-b*b)))

#сумма квадратов разности координат

nan


<ipython-input-27-6629b38f20ee>:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np.sum(a*a-b*b)))


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [28]:
file_path="/Users/izuard/Desktop/Ai/Sources/minutes_n_ingredients.csv"

In [29]:
source=np.loadtxt(file_path,dtype=np.int32,delimiter=',',skiprows=1)
source[:5,:]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [30]:
array_min=np.min(source[:,1:],axis=0)
array_max=np.max(source[:,1:],axis=0)
array_avg=np.average(source[:,1:],axis=0)
array_med=np.median(source[:,1:],axis=0)
print("min: ",array_min,"\nmax: ",array_max,"\navg: ",array_avg,"\nmed: ",array_med)

min:  [0 1] 
max:  [2147483647         39] 
avg:  [2.16010017e+04 9.05528000e+00] 
med:  [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [31]:
q=0.75
quant=np.quantile(source[:,1],q)
source1=source[source[:,1]<=quant]
source1

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [32]:
nums=np.count_nonzero((source[:,1]==0))
print(nums)

source[:,1]=np.where(source[:,1]==0,1,source[:,1])

nums=np.count_nonzero((source[:,1]==0))
print(nums)

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [33]:
np.unique(source, axis=1).size/3

100000.0

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [34]:
un=np.unique(source[:,2])
print(un.size)
un

37


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39], dtype=int32)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [35]:
bybyby=source[source[:,2]<=5]
bybyby

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
aloha=source[:,2]/source[:,1]
print(np.max(aloha))
aloha

24.0


array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
srt=source[source[:,1].argsort()]
srt=srt[::-1]
np.average(srt[:100,2],axis=0)

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [38]:
source[rnd.randint(0,len(source)+1,10)]

array([[281149,     35,     15],
       [158949,     40,     11],
       [309308,     25,     10],
       [160067,     30,     13],
       [402877,     50,      9],
       [302527,     35,      6],
       [ 21352,    165,     14],
       [247356,      5,      4],
       [274781,     40,      9],
       [351162,    195,      8]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [39]:
ingr_avg=np.average(source[:,2])
result=np.count_nonzero(source[:,2]<ingr_avg)/(len(source)/100)
result

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [40]:
is_simple=np.where((source[:,1]<=20) & (source[:,2]<=5), 1,0)
new_arr=np.insert(source,3,is_simple,axis=1)
new_arr

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [41]:
result=np.sum(new_arr[:,3])/(len(new_arr)/100)
result

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [42]:
first_group=source[source[:,1]<10]
msgr=source[source[:,1]>=10]
second_group=msgr[msgr[:,1]<=20]
third_group=source[source[:,1]>20]

length=np.amin([len(first_group),
                len(second_group),
                len(third_group)])

so_big=np.array([first_group[:length,:],
                 second_group[:length,:],
                 third_group[:length,:]])
so_big.shape

(3, 7588, 3)